### ISSUE TITLE
Chokidar doesn't notice changes inside Docker

### ISSUE THREAD

**Issue by cullylarson** [paulmillr/chokidar#1051]
**Describe the bug**

I have an app running inside docker that uses chokidar to respond to file changes. The app folder is mounted as a volume. When I make a change from the host machine (i.e. during development), chokidar doesn't notice the change. I confirmed that the file is actually changed in the container. Also, if polling is enabled, the change is noticed. And if I change the file from inside the docker container (i.e. bash into the container, modify a file), chokidar sees that change as well.

**Versions:**
 - Chokidar version: 3.4.3
 - Node version: v12.18.1 (also tried with v14.15.1 and v15.3.0)
 - OS version: I'm running macos on my host machine. The Docker container is running Alpine 9.2.0.

**To Reproduce:**

I created a repo that reproduces the issue: https://github.com/cullylarson/chokidar-watch-issue

**Expected behavior**

Chokidar should see changes made from the host machine to files mounted inside a Docker container.

**Comment by UchihaYuki** [comment]
Any progress on this issue?

**Comment by paulmillr** [comment]
@UchihaYuki you can start working on the issue and show some progress to us. What do you think? Can you do that?

**Comment by tmont** [comment]
This has probably been fixed in recent versions of Docker. I'm using Docker for Linux and it was fixed in 4.15.0. Some more details here: https://github.com/docker/desktop-linux/issues/30

**Comment by Geczy** [comment]
not fixed, still having this issue. can you show some progress please @paulmillr

**Comment by paulmillr** [comment]
@Geczy sure. Pay me.

**Comment by Geczy** [comment]
> @Geczy sure. Pay me.

whats your address ill mail you a check 🥇

**Comment by paulmillr** [comment]
No checks, only crypto or github sponsorship.

**Comment by abdonrd** [comment]
Is there any news about this? Thanks! 🙏

**Comment by Geczy** [comment]
@abdonrd sure, pay him

**Comment by sekjal** [comment]
@paulmillr do you a quote for how much money it would take to get this issue resolved?

**Comment by paulmillr** [comment]
@sekjal we can discuss in email if you have some funding, but my focus is on other libraries these days.

**Comment by paulmillr** [comment]
The backlog is going to start from zero as a preparation for v4 release. v4 would bring massive rewrite to the table and drop most dependencies. All issues are being closed as preparation for v4 release.

In the future, only issues with enough community support would be considered.

See issue 1195 for more info. Thank you.
