### ISSUE TITLE
Not watching symlinked folders

### ISSUE THREAD

**Issue by TheAlphaNerd** [paulmillr/chokidar#223]
In our current workflow we are using ```npm link``` during development to work on multiple modules simultaneously.

We currently noticed that watchify was not registering changes on all of our files... this makes us sad.

In particular this is happening with files that are more than three levels deep.  I'll try and make a standalone example with tests soon.

**Comment by es128** [comment]
This specific use case was addressed a little while ago: https://github.com/substack/watchify/issues/109

And the [symlink tests](https://github.com/paulmillr/chokidar/blob/master/test.js#L477) cover this situation as well.

Please make sure your deps are up to date, and if there's still a problem I'll need your example repo and instructions to reproduce in order to help figure out what's wrong.

**Comment by TheAlphaNerd** [comment]
Yeah... I was heavily involved in that last symlink issue.  Deps are definitely up to date.  I'll put together an example repo, or perhaps an extra unit test, that shows the problem.  Thanks for the prompt response.

**Comment by es128** [comment]
any update?

**Comment by TheAlphaNerd** [comment]
Haven't had a chance to out together a stand alone example yet. We as
hoping to take some time this week to do so

**Comment by TheAlphaNerd** [comment]
So I have an example for you... and the behavior is SUPER ODD

--> https://github.com/TheAlphaNerd/uatu/

Compare master with the branch "works".  Basically as long as we don't go past a depth of three folders everything works as expected.  If we have a symlinked folder of a depth of more than three folders everything hangs.... wat?

You can also check out the branch 'also-broken' which doesn't event attempt to test the symlinks, but watching on normal files explodes if the symlinked folder simply exists.  You can compare it with 'but-this-works' to see that the exact same suite works if we don't make the symlink.

I am currently at a loss as to what is going on, hopefully this is a good start

**Comment by es128** [comment]
Which OS are you testing on?

**Comment by TheAlphaNerd** [comment]
osx 10.9.5

**Comment by es128** [comment]
I don't know what's going on with your test script, but when I just plug in the file tree you generated into the example.js script, everything seems fine:

```
λ node example.js
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/one
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/index.js
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/one/two
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/index.js
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/one/two/three
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/one/two/index.js
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/one/two/three/four
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/one/two/three/index.js
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two/three
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two/index.js
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/one/two/three/four/index.js
addDir /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two/three/four
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two/three/index.js
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two/three/four/index.js
ready
change /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/first/one/two/three/four/index.js
change /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two/three/four/index.js
^C%
```

**Comment by es128** [comment]
and when watching just the specific file, as your tests do:

```
λ node example.js
add /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two/three/four/index.js
ready
change /var/folders/7b/b3l6wm011b315rrgj0svf5h4xdcfcv/T/uatu-1423699834333/second/one/two/three/four/index.js
```

**Comment by es128** [comment]
ok here I fixed it

```diff
diff --git i/test/test-symlink.js w/test/test-symlink.js
index 747c30d..692ad2f 100644
--- i/test/test-symlink.js
+++ w/test/test-symlink.js
@@ -45,8 +45,9 @@ function testFolder(folder, t) {
   watcher.on('change', function (event) {
     t.ok(1, event);
     watcher.close();
+  }).on('ready', function() {
+    writeIt(folder);
   });
-  writeIt(folder);
 }

 test('symlink: setup', function (t) {
@@ -83,5 +84,5 @@ test('change to a deeper symlinked file (depth of three)', function (t

 // FIXME comment below to make things not hang
 test('change to a deepest symlinked file (depth of four)', function (t) {
-  test(onceRemovedDeepest, t);
+  testFolder(onceRemovedDeepest, t);
 });
```

**Comment by TheAlphaNerd** [comment]
@es128 even with this fix I still have the test not running when I symlink the folder.

**Comment by es128** [comment]
You're probably still getting an `add` event instead of `change`. The timing of your test script is wonky, which is why you were getting inconsistent behavior. You have to ensure you leave sufficient time between the creation of a file and changing it.

**Comment by TheAlphaNerd** [comment]
@es128 adding a set timeout indeed fixed the tests.  I am still experiencing odd behavior with watchify... I will continue to try and reproduce it.
