### ISSUE TITLE
chokidar doesn't notice changes when paths is globs-array

### ISSUE THREAD

**Issue by EthanZhong** [paulmillr/chokidar#698]
```javascript
	const Globs={
		js:'**/*.js',
		scss:'**/*.scss',
		html:'**/*.html'
	};
	chokidar.watch([Globs.js,Globs.scss,Globs.html], {
        cwd: path.resolve(__dirname,'src'),
        ignoreInitial: true,
        awaitWriteFinish: {
            stabilityThreshold: 600
        }
    }).on('change', path => {
        console.log(`ChangeFile===>${path}`);
    });
```
everything run good,except the html file in deep directory,when i modify the file (`src/a/b/c/d.html`) chokidar doesn't notice changes

**Comment by tasos-ch** [comment]
I believe I have the same issue.

I have tried to debug it and I think I have somehow isolated the failure to the case where the `paths` parameter of `chokidar.watch()` is an array where `array.length ≥ 2`.

For example, the following paths will have no issues:
1. `['./index.js']`
1. `['./**/*.js']`

However, the following array will:
```
[
  './index.js',
  './**/*.js'
]
```
Specifically, in the last case `chokidar` will emit an `unlink` event on `./index.js` after changing and saving the file once or twice and after that `unlink` event no more changes will be identified.

I have created a [repository](https://github.com/tasos-ch/gulp-watch-test) where I describe the above three test cases that reproduce this issue.

**Possible Solution**
One possible solution is to create two watchers:
```
chokidar.watch('./index.js');
chokidar.watch('./**/*.js');
```

However, with more paths this may prove problematic due to the big number of watchers. So, I am not very sure this is a valid workaround for most cases.

**Comment by paulmillr** [comment]
Update to v3, it should resolve this.

**Comment by reischapa** [comment]
Hello, 

That did not solve the problem for me.

I have cloned the repo, and on branch `master` I have changed the provided `example.js` file in order to make it look like this: 

```js
global.watcher = require('./').watch(['a.js', 'b.js'], {
  ignored: /node_modules|\.git/,
  persistent: true,
  // followSymlinks: false,
  // useFsEvents: false,
  // usePolling: false
}).on('all', function(event, path) {
  console.log(event, path);
}).on('ready', function() {
  console.log('Ready');
})
//.on('raw', console.log.bind(console, 'RawEvent:'))
```
After creating the files `a.js` and `b.js` inside the `chokidar` dir and running `node example.js`, I successfully get events for changes on `a.js`, but for `b.js`, I just get an `unlink`event and nothing else after that. Example output:

```
add a.js
add b.js
Ready
change a.js

change a.js
change a.js
unlink b.js
```

And then changes on `b.js`stop firing events altogether.

Funny enough, and I just realized this when writing this post, if I edit `b.js` _first_ and then `a.js`, I get the unlink event on `a.js`, and then changes are ignored on _that_ file. So, I'm guessing this is not an indexing issue.

PS: I came about this issue because [nodemon](https://github.com/remy/nodemon) is (for me) not working properly when defining multiple `--watch` input options, and after doing some digging I realized it uses `chokidar` (v2, still), and that it passes an array as the first input argument, with an element for each `--watch` option.

**Comment by paulmillr** [comment]
I’m not sure what’s different on your system from all the users which have it working (us included). We need more context.

**Comment by reischapa** [comment]
I'm using Arch Linux: 

```
$ uname -a
Linux <hostname> 5.2.9-zen1-1-zen #1 ZEN SMP PREEMPT Fri Aug 16 11:32:38 UTC 2019 x86_64 GNU/Linux
```
Node 10, NPM 6.11.2 (just updated, issue still present). I have also issued `npm cache clean --force`, deleted the `node_modules` folder, and re-issued `npm install`. The issue is still present. 

Is there any additional information I can provide you with?

**Comment by reischapa** [comment]
Breaking news: I was using vim to edit the files. If I use `echo` with redirection `chokidar` works properly. So this must be an issue with the way the saving process is being done, since I do know vim uses temp and backup files in some situations.

I'm going to run some tests and get back to you.

**Comment by paulmillr** [comment]
Try playing with awaitWriteFinish and usePolling  options.

**Comment by reischapa** [comment]
I have read somewhere that using nodemon's `-L` flag solves the problem, which I think means using `usePolling` for `chokidar`. I'll try to use that as a workaround.

But this is very strange. Because in my tests this issue happens only when you pass an array to `chokidar`, only when that array has more than one element, and only when writing files using vim. 

Don't you find this odd?
